Add Hyperledger Indy Node blueprint
aws-samples/aws-blockchain-node-runners pull request #40
Opened 2024-01-25 04:09 UTC by KatsuyaMatsuoka

### What does this PR do?

#33 

Add Hyperledger Indy blueprint, CDK assets and docs.
It creates Indy Trustee and Steward Nodes.

🛑 Please open an issue first to discuss any significant work and flesh out details/direction - we would hate for your time to be wasted.
Consult the [CONTRIBUTING](https://github.com/aws-samples/aws-blockchain-node-runners/blob/main/CONTRIBUTING.md#contributing-via-pull-requests) guide for submitting pull-requests.

### Motivation

### More

- [ ] Yes, I have tested the PR using my local account setup (Provide any test evidence report under Additional Notes)
- [ ] Mandatory for new node blueprints. Yes, I have added usage example to the `README.md` file in my blueprint folder
- [ ] Mandatory for new node blueprints. Yes, I have implemented automated tests for all stacks in my blueprint and they pass
- [ ] Mandatory for new node blueprints. Yes, I have added a reference to my `README.md` file to `website/docs` section for this feature
- [ ] Yes, I have set up and ran all [pre-merge quality control tools](./docs/pre-merge-tools.md) on my local machine and they don't show warnings.

### For Moderators

- [ ] The tests for all current blueprints successfully complete before merge?
- [ ] Mandatory for new node blueprints. All [pre-merge quality control tools](./docs/pre-merge-tools.md) and `cdk-nag` tools don't show warnings?
- [ ] Mandatory for new node blueprints. The deployment test works on blank AWS account according to instructions in the `README.md` before merge?
- [ ] Mandatory for new node blueprints. The website builds without errors?

### Additional Notes

2024-02-09 06:08 UTC, frbrkoala requested changes
Need your help to make changes to the CDK and add some clarity to the instructions in the README. Got stuck on step "Generating Genesis Files" and could not continue because could not figure out where to download the files from.

Overall, it looks like the current instructions include a lot of manual steps. Is it possible to script them up so that the network will get up and running all together automatically?

2024-02-09 06:08 UTC, frbrkoala commented on lib/indy/README.md
> +1. Download each sheet (Stewards, Trustees) containing the information generated in the steps so far
Need guidance where I should go to download the files from? I've got stuck on this step and could not continue.

2024-03-14 08:15 UTC, KatsuyaMatsuoka commented on lib/indy/lib/constructs/indy-node-instance.ts
> +          volumeType: ec2.EbsDeviceVolumeType.STANDARD,
According to the community doc I referred to, the magnetic standard is recommended for cost reduction, so I adopted this one, but I think there is no problem with GP3.

https://github.com/hyperledger/indy-node/blob/2b61cd8340886945d550eb8a5218ab3d71223668/docs/source/install-docs/AWS-NodeInstall-20.04.md?plain=1#L45

2024-03-14 08:17 UTC, KatsuyaMatsuoka commented on lib/indy/lib/constructs/indy-node-instance.ts
> +      instanceType: ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.LARGE),
I chose T3.large based on community doc, but I think M5 is better when considering use in production environments.

https://github.com/hyperledger/indy-node/blob/2b61cd8340886945d550eb8a5218ab3d71223668/docs/source/install-docs/AWS-NodeInstall-20.04.md?plain=1#L21

2024-04-05 06:35 UTC, merged